// <auto-generated />
using System;
using HomeLabCore.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeLabCore.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801210723_AddChatIdToMediaSubscription")]
    partial class AddChatIdToMediaSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeLabCore.Domain.Entities.Media.MediaSearchSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MediaSearchSnapshots");
                });

            modelBuilder.Entity("HomeLabCore.Domain.Entities.Media.MediaSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MediaExternalId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MediaExternalId", "MediaType");

                    b.ToTable("MediaSubscriptions");
                });

            modelBuilder.Entity("HomeLabCore.Domain.Entities.Media.MediaSearchSnapshot", b =>
                {
                    b.OwnsMany("HomeLabCore.Domain.Entities.Media.MediaSearchSnapshotEntry", "Results", b1 =>
                        {
                            b1.Property<Guid>("MediaSearchSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FirstAirDate");

                            b1.Property<int>("Id");

                            b1.Property<int>("MediaType");

                            b1.Property<string>("Overview")
                                .IsRequired();

                            b1.Property<string>("PosterPath");

                            b1.Property<string>("ReleaseDate");

                            b1.Property<int>("Status");

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.HasKey("MediaSearchSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("MediaSearchSnapshots");

                            b1
                                .ToJson("Results")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaSearchSnapshotId");
                        });

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
